#ifndef CONSTANTS_H
#define CONSTANTS_H

double Gamma = 1.17;
double R     = 8314.46261815324;   // J/K/kmol
double Pr    = 0.75;               // dimensionless
double one_atm_Pa = 101325.0;      // pa
double M     = 21.0;               // molecular mass
double A     = 6.85*1e9;           // m3/kgs
double q     = 43.28;              // must be scaled RT0/M
double Ea    = 46.37;              // must be scaled RT0
double T0    = 300.0;              // K

#endif